default_agent: main
agents:
  main:
    name: main
    entrypoint: main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::412602263780:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-0d6e4079e3
      execution_role_auto_create: false
      account: '412602263780'
      region: us-east-1
      ecr_repository: 412602263780.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-main
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: main-7rUSst3r7E
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:412602263780:runtime/main-7rUSst3r7E
      agent_session_id: f56a1f23-75f2-4b18-8809-03980447823a
    codebuild:
      project_name: bedrock-agentcore-main-builder
      execution_role: arn:aws:iam::412602263780:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-0d6e4079e3
      source_bucket: bedrock-agentcore-codebuild-sources-412602263780-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: main_mem-NVs3522m2p
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:412602263780:memory/main_mem-NVs3522m2p
      memory_name: main_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
